# Fetch base image
FROM ubuntu

# Avoid prompts during install 
ENV DEBIAN_FRONTEND=noninteractive

# Setup work directory & configuration files
WORKDIR /encryptUtil/
COPY requirements.txt /encryptUtil/requirements.txt
COPY interface.py /encryptUtil/interface.py
COPY src/ /encryptUtil/src/
COPY cases/ /encryptUtil/cases

# Get & install necessary tools on image
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get update
RUN apt-get install -y build-essential libgtk-3-dev libboost-python-dev
RUN apt-get install -y python-dev python3-dev python3-pip
RUN pip3 install --upgrade pip

RUN pip install -r requirements.txt
# only use python shell
ENTRYPOINT ["python3","interface.py"]

# To run use :
# $ docker run -it name:version bash

# To attach persistant volume use:
# $ docker run -it -v <Folder Name>:<Some Arbitrary Folder on the instance> name:version python bash